query products($limit: Int) {
  categories(limit: $limit) {
    slug
    translations {
      content
      title
      description
      cover {
        id
      }
      languages_code {
        code
        direction
      }
    }
  }
}


query productsapps($limit: Int) {
  applications(limit: $limit) {
    slug

    translations {
      title
      description
      content
      cover {
        id
      }
      languages_code {
        code
      }
    }
  }
}

