query projects($filter:String) {
  projects_categories(filter:{slug:{_eq:$filter}}) {
    slug
    translations{
      languages_code {
          code
        }
        title
    }
    projects {
      slug
      translations {
        languages_code {
          code
        }
        title
        description
        content
        cover {
          id
        }
      }
    }
  }
}
query allprojects {
  projects_categories {
    slug
    translations{
      languages_code {
          code
        }
        title
    }
    projects {
      slug
      translations {
        languages_code {
          code
        }
        title
        description
        content
        cover {
          id
        }
      }
    }
  }
}
